import type { Question } from "./questions";

const F0_SYSTEM_VALUES = [
  "f0_q_erp", "f0_q_qms", "f0_q_gw",
  "f0_p_erp", "f0_p_mes", "f0_p_erpmes",
  "f0_d_erp", "f0_d_mes", "f0_d_aps",
];

const F0_1_CORE = ["f0_1_erp", "f0_1_mes", "f0_1_qms"];

void F0_SYSTEM_VALUES;

export const SECTION_F_QUESTIONS: Question[] = [
  {
    id: "F0-Q1",
    type: "single",
    title:
      "품질 관련 데이터(NCR·CAPA·Audit·검사)는 주로 어떻게 관리합니까?",
    required: true,
    options: [
      { value: "f0_q_manual", label: "수기·종이" },
      { value: "f0_q_excel", label: "엑셀·공유폴더" },
      { value: "f0_q_gw", label: "그룹웨어" },
      { value: "f0_q_erp", label: "ERP 품질 모듈" },
      { value: "f0_q_qms", label: "전문 QMS" },
      { value: "f0_q_outsrc", label: "외부 위탁" },
      { value: "f0_q_unknown", label: "모름 / 해당 없음" },
    ],
  },
  {
    id: "F0-Q2",
    type: "single",
    title: "생산·공정 데이터(작업지시·실적·불량)는 주로 어떻게 관리합니까?",
    required: true,
    options: [
      { value: "f0_p_manual", label: "수기" },
      { value: "f0_p_excel", label: "엑셀" },
      { value: "f0_p_erp", label: "ERP 생산 모듈" },
      { value: "f0_p_mes", label: "MES" },
      { value: "f0_p_erpmes", label: "ERP + MES 연계" },
      { value: "f0_p_unknown", label: "모름" },
    ],
  },
  {
    id: "F0-Q3",
    type: "single",
    title: "납기·수주 관련 정보는 주로 어떻게 관리합니까?",
    required: true,
    options: [
      { value: "f0_d_oral", label: "담당자 구두·개인 관리" },
      { value: "f0_d_excel", label: "엑셀" },
      { value: "f0_d_erp", label: "ERP / 생산관리" },
      { value: "f0_d_mes", label: "MES 연동" },
      { value: "f0_d_aps", label: "별도 APS·스케줄러" },
      { value: "f0_d_unknown", label: "모름" },
    ],
  },
  {
    id: "F0-1",
    type: "multi",
    title: "(Deep Dive) 귀사에 정식 도입·운영 중인 시스템을 모두 선택해 주십시오.",
    required: true,
    showIf: {
      or: [
        { questionId: "F0-Q1", anyOf: ["f0_q_erp", "f0_q_qms", "f0_q_gw"] },
        { questionId: "F0-Q2", anyOf: ["f0_p_erp", "f0_p_mes", "f0_p_erpmes"] },
        { questionId: "F0-Q3", anyOf: ["f0_d_erp", "f0_d_mes", "f0_d_aps"] },
      ],
    },
    options: [
      { value: "f0_1_erp", label: "ERP", hasText: true },
      { value: "f0_1_mes", label: "MES / 생산실적 수집" },
      { value: "f0_1_plm", label: "PLM / CAD·BOM" },
      { value: "f0_1_qms", label: "전문 QMS" },
      { value: "f0_1_gw", label: "그룹웨어" },
      { value: "f0_1_bi", label: "BI / 데이터웨어하우스" },
      { value: "f0_1_none", label: "위 없음 — 엑셀·수기 중심", exclusive: true },
      { value: "f0_1_etc", label: "기타", hasText: true },
    ],
  },
  {
    id: "F0-1b",
    type: "single",
    title: "(Deep Dive) 주력 시스템(ERP/MES/QMS)의 배포·운영 형태는?",
    required: true,
    showIf: { questionId: "F0-1", anyOf: F0_1_CORE },
    options: [
      { value: "deploy_onprem", label: "자체 서버(온프레) — 사내 DC·폐쇄망" },
      { value: "deploy_private", label: "프라이빗 클라우드 (전용 VPC)" },
      { value: "deploy_saas", label: "퍼블릭 SaaS — 벤더 클라우드 구독" },
      { value: "deploy_hybrid", label: "혼합 (핵심 온프레 + 일부 SaaS)" },
      { value: "deploy_unknown", label: "모름" },
    ],
  },
  {
    id: "F0-2",
    type: "single",
    title: "(Deep Dive) 위 시스템들 간 데이터 연동 수준은?",
    required: true,
    showIf: { questionId: "F0-1", minIncludes: 2 },
    options: [
      { value: "integ_none", label: "거의 없음 — 부서·파일별 분리" },
      { value: "integ_excel", label: "엑셀 export/import 수준" },
      { value: "integ_core", label: "수주→생산→출하 등 핵심 흐름만 연동" },
      { value: "integ_quality", label: "불량·NCR까지 연동" },
      { value: "integ_unknown", label: "모름" },
    ],
  },
  {
    id: "F0-3",
    type: "single",
    title: "향후 품질·ISO 실행을 디지털화한다면, 1순위로 선호하는 접근은?",
    required: true,
    options: [
      { value: "pref_erp", label: "기존 ERP에 품질 모듈 확장" },
      { value: "pref_mes", label: "MES와 연계 (현장 실적·불량)" },
      { value: "pref_qms", label: "독립 QMS (NCR/CAPA/Audit) + ERP/MES API 연계" },
      { value: "pref_saas", label: "독립 SaaS(클라oud) — 빠른 도입·구독" },
      { value: "pref_onprem", label: "사내 서버 구축(온프레) — 보안·망분리" },
      { value: "pref_excel", label: "엑셀·그룹웨어 고도화 (신규 시스템 없음)" },
      { value: "pref_tbd", label: "PoC·벤치마크 후 결정" },
    ],
  },
  {
    id: "F0-3-1",
    type: "multi",
    title: "(Deep Dive) 1순위를 선택한 주된 이유는? (최대 2개)",
    max: 2,
    required: true,
    showIf: {
      questionId: "F0-3",
      anyOf: [
        "pref_erp", "pref_mes", "pref_qms", "pref_saas",
        "pref_onprem", "pref_excel", "pref_tbd",
      ],
    },
    options: [
      { value: "f0_3_1_policy", label: "IT·전사 정책과의 정합" },
      { value: "f0_3_1_cost", label: "초기 도입·운영 비용" },
      { value: "f0_3_1_ux", label: "현장 사용 편의 (학습·입력 부담)" },
      { value: "f0_3_1_invest", label: "기존 ERP·MES 투자 활용" },
      { value: "f0_3_1_sec", label: "보안·망분리" },
      { value: "f0_3_1_lock", label: "벤더 lock-in 회피" },
      { value: "f0_3_1_audit", label: "경영진·고객 Audit 설득 용이" },
      { value: "f0_3_1_etc", label: "기타", hasText: true },
    ],
  },
  {
    id: "F0-3-2",
    type: "single",
    title: "(Deep Dive) 2순위로 검토 가능한 형태는? (1순위와 다른 항목 1개)",
    required: true,
    showIf: { questionId: "F0-3", notValue: "pref_tbd" },
    optionsFrom: "F0-3",
    options: [
      { value: "pref_erp", label: "기존 ERP에 품질 모듈 확장" },
      { value: "pref_mes", label: "MES와 연계 (현장 실적·불량)" },
      { value: "pref_qms", label: "독립 QMS (NCR/CAPA/Audit) + ERP/MES API 연계" },
      { value: "pref_saas", label: "독립 SaaS(클라oud) — 빠른 도입·구독" },
      { value: "pref_onprem", label: "사내 서버 구축(온프레) — 보안·망분리" },
      { value: "pref_excel", label: "엑셀·그룹웨어 고도화 (신규 시스템 없음)" },
    ],
  },
  {
    id: "F0-4",
    type: "single",
    title:
      "(Deep Dive) 품질·공정 데이터를 외부(클라oud·SaaS·AI)에 올릴 때, 내부 기준상 가장 큰 제약은?",
    required: true,
    options: [
      { value: "data_cust", label: "고객사·계약상 데이터 반출 제한" },
      { value: "data_process", label: "영업·공정 기밀" },
      { value: "data_hr", label: "개인정보·노무 관련" },
      { value: "data_onprem", label: "IT 정책상 온프레만 허용" },
      { value: "data_none", label: "특별한 제약 없음" },
      { value: "data_nodiscuss", label: "아직 논의·기준 없음" },
      { value: "data_etc", label: "기타", hasText: true },
    ],
  },
  {
    id: "F5-1",
    type: "multi",
    title:
      "품질·운영 디지털 도구 도입을 막거나 지연시키는 요인 영향력 TOP 3를 골라 주십시오.",
    exact: 3,
    required: true,
    options: [
      { value: "f5_1_roi", label: "예산·ROI 불확실" },
      { value: "f5_1_staff", label: "품질·현장 전담 인력 부족" },
      { value: "f5_1_priority", label: "경영진 우선순위 (품질 vs 생산·납기)" },
      { value: "f5_1_data", label: "데이터 품질·표준화 부족" },
      { value: "f5_1_sec", label: "IT·보안·망분리 정책" },
      { value: "f5_1_dup", label: "기존 ERP/MES와 중복·충돌" },
      { value: "f5_1_resist", label: "현장 변화 저항·추가 입력 부담" },
      { value: "f5_1_ref", label: "검증 사례·레퍼런스 부족" },
      { value: "f5_1_vendor", label: "벤더·유지보수 리스크" },
      { value: "f5_1_na", label: "해당 없음 / 도입 계획 없음", exclusive: true },
    ],
  },
  {
    id: "F6",
    type: "single",
    title: "예산이 한정되어 있다면, 가장 먼저 유료로 도입·검증하고 싶은 역량은?",
    required: true,
    options: [
      { value: "mvp_audit", label: "Audit·내부심사 증빙·기록 자동 점검" },
      { value: "mvp_capa", label: "CAPA/8D 초안·워크플로 자동화" },
      { value: "mvp_check", label: "ISO 조항 → 현장 체크시트·일상 점검" },
      { value: "mvp_trace", label: "불량 발생 단계·재발 추적·분석" },
      { value: "mvp_kpi", label: "경영진 KPI·손실비용 리포트" },
      { value: "mvp_hub", label: "ERP/MES 연동 데이터 허브" },
      { value: "mvp_tbd", label: "아직 불명 — PoC 결과 후 결정" },
    ],
  },
  {
    id: "F6-1",
    type: "single",
    title: "(Deep Dive) 1순위 역량에 월 구독·라이선스 지불 의향은?",
    required: true,
    showIf: { questionId: "F6", notValue: "mvp_tbd" },
    options: [
      { value: "f6_1_now", label: "즉시 검토 (담당자 미팅 희망)" },
      { value: "f6_1_poc", label: "PoC·ROI 확인 후" },
      { value: "f6_1_pilot", label: "무료·저가 파일럿만" },
      { value: "f6_1_no", label: "12개월 내 계획 없음" },
    ],
  },
  {
    id: "F6-2",
    type: "multi",
    title: "(Deep Dive) PoC·파일럿에서 반드시 검증하고 싶은 KPI (최대 2개)",
    max: 2,
    required: true,
    showIf: { questionId: "F6-1", anyOf: ["f6_1_poc", "f6_1_pilot"] },
    options: [
      { value: "f6_2_capa", label: "CAPA 리드타임 단축" },
      { value: "f6_2_audit", label: "Audit 준비 man-day 감소" },
      { value: "f6_2_recur", label: "동일 불량 재발률 감소" },
      { value: "f6_2_defect", label: "불량·재작업률 감소" },
      { value: "f6_2_otd", label: "납기준수율 개선" },
      { value: "f6_2_time", label: "품질 담당자 업무시간 절감" },
      { value: "f6_2_rpt", label: "경영 보고 자동화" },
      { value: "f6_2_etc", label: "기타", hasText: true },
    ],
  },
  {
    id: "F5-2",
    type: "single",
    title: "(Deep Dive) 도입을 실질 승인·예산 집행할 수 있는 의사결정 구조는?",
    required: true,
    showIf: { questionId: "F6-1", anyOf: ["f6_1_now", "f6_1_poc"] },
    options: [
      { value: "f5_2_dept", label: "품질·생산 부서장 자체 예산·결정" },
      { value: "f5_2_exec", label: "대표·경영진 승인 (품의·IT 검토)" },
      { value: "f5_2_group", label: "본사·그룹 IT 표준·구매 주도" },
      { value: "f5_2_cust", label: "고객사 요구 (Audit·협력사 등록)가 촉발" },
      { value: "f5_2_none", label: "아직 논의 단계 없음" },
    ],
  },
];
